version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - yarn install
  build:
    commands:
      - node ./preinstall.js
      - yarn build

artifacts:
  files:
    - public/*
  discard-paths: yes
cache:
  paths:
    - node_modules/** /*
